/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package szineszek;

import java.util.ArrayList;
import java.util.Date;
import java.io.*;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kincses.marcell
 */
public class adatok extends javax.swing.JFrame {

    ArrayList<SzineszekClass> szineszekClassList = new ArrayList<>();
    DefaultTableModel model;
    
    public adatok() {
        initComponents();
        this.model = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtNev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtFerfi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSzulIdo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtSzulHely = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtSzulOrsz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtFilmszam = new javax.swing.JTextField();
        jbtnModositas = new javax.swing.JButton();
        jbtnUjAdatFelvitel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Név", "Férfi", "Születési idő", "Születés hely", "Szül. ország", "Filmszám"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Név:");

        jtxtNev.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Férfi:");

        jtxtFerfi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Születési idő:");

        jtxtSzulIdo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Születési hely:");

        jtxtSzulHely.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Születési ország:");

        jtxtSzulOrsz.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Filmszám:");

        jtxtFilmszam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jbtnModositas.setText("Módosítás");
        jbtnModositas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModositasActionPerformed(evt);
            }
        });

        jbtnUjAdatFelvitel.setText("Új adat felvitele");
        jbtnUjAdatFelvitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUjAdatFelvitelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNev, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jtxtFerfi)
                            .addComponent(jtxtSzulIdo))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtSzulHely, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jtxtSzulOrsz, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jtxtFilmszam))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnModositas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnUjAdatFelvitel, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtFerfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtSzulIdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtSzulHely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtSzulOrsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtxtFilmszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnModositas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnUjAdatFelvitel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
         //Csatlakozás az adatbázishoz
        String host = "jdbc:mysql://localhost:3306/javaszinesz?zeroDateTimeBehavior=convertToNull";
        String username = "root";
        String password = "";
        
        //SQL adatok lekérdezése
        try {
        Connection con = (Connection) DriverManager.getConnection(host, username, password);       
        Statement stmt = con.createStatement();
        String sql = "SELECT * FROM javaszinesz";
        ResultSet rs = stmt.executeQuery(sql);
        
            SzineszekClass szineszek;
            while(rs.next())
            {
                szineszek = new SzineszekClass(rs.getString("NEV"),rs.getBoolean("FERFI") ,rs.getString("SZULIDO"), rs.getString("SZULHELY"), rs.getString("SZULORSZ"), rs.getInt("FIlMSZAM"));
                szineszekClassList.add(szineszek);
                   
            }
            stmt.close();
            con.close();
            
        } catch (Exception e) {
             
             System.out.println(e.getMessage());
        }
        
        //adattábla feltöltése
        for (SzineszekClass f : szineszekClassList){
            model.addRow(new Object[]{f.getNev(),f.getFerfi(),f.getSzulido(),f.getSzulhely(),f.getSzulorsz(),f.getFilmszam()});
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jbtnUjAdatFelvitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUjAdatFelvitelActionPerformed
        // TODO add your handling code here:
        UjAdat ujAdatFelvitel = new UjAdat();
        ujAdatFelvitel.setVisible(true);
        
    }//GEN-LAST:event_jbtnUjAdatFelvitelActionPerformed

    
    String nev;
    Boolean ferfi;
    String szulido;   
    String szulhely;
    String szulorsz;
    Integer filmszam;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int sor = jTable1.getSelectedRow();
       
        
       nev = jTable1.getModel().getValueAt(sor, 0).toString();
       ferfi = Boolean.parseBoolean( jTable1.getModel().getValueAt(sor, 1).toString() );
       szulido = jTable1.getModel().getValueAt(sor, 2).toString();
       szulhely = jTable1.getModel().getValueAt(sor, 3).toString();
       szulorsz = jTable1.getModel().getValueAt(sor, 4).toString(); 
       filmszam = Integer.parseInt( jTable1.getModel().getValueAt(sor, 5).toString() );
       
       jtxtNev.setText(nev);
       jtxtFerfi.setText(ferfi.toString());
       jtxtSzulIdo.setText(szulido);
       jtxtSzulHely.setText(szulhely);
       jtxtSzulOrsz.setText(szulorsz);
       jtxtFilmszam.setText(filmszam.toString());
       
                
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnModositasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModositasActionPerformed
    String nevModosit = jtxtNev.getText();
    Boolean ferfiModosit = Boolean.parseBoolean(jtxtFerfi.getText());
    String szulidoModosit = jtxtSzulIdo.getText();   
    String szulhelyModosit = jtxtSzulHely.getText();
    String szulorszModosit = jtxtSzulOrsz.getText();
    Integer filmszamModosit = Integer.parseInt(jtxtFilmszam.getText());
        
//Csatlakozás az adatbázishoz
        String host = "jdbc:mysql://localhost:3306/javaszinesz?zeroDateTimeBehavior=convertToNull";
        String username = "root";
        String password = "";

        try {
            Connection con = (Connection) DriverManager.getConnection(host, username, password);
            String sql = "UPDATE javaszinesz SET NEV='"+nevModosit+"' ,FERFI="+ferfiModosit+",SZULIDO='"+szulidoModosit+"',SZULHELY='"+szulhelyModosit+"',SZULORSZ='"+szulorszModosit+"',FILMSZAM="+filmszamModosit+""
            + "WHERE NEV='"+nev+"'" ;
            Statement stmt = con.createStatement();
            stmt.executeUpdate(sql);
            stmt.close();
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_jbtnModositasActionPerformed
     
            
        

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adatok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new adatok().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnModositas;
    private javax.swing.JButton jbtnUjAdatFelvitel;
    private javax.swing.JTextField jtxtFerfi;
    private javax.swing.JTextField jtxtFilmszam;
    private javax.swing.JTextField jtxtNev;
    private javax.swing.JTextField jtxtSzulHely;
    private javax.swing.JTextField jtxtSzulIdo;
    private javax.swing.JTextField jtxtSzulOrsz;
    // End of variables declaration//GEN-END:variables
}
